name: Civilization
version: @version@
main: com.hirises.civilization.Civilization
api-version: 1.18
depend:
  - Core1.18
  - WorldEdit
loadbefore:
  - Core1.18
commands:
  menu:
  money:
  civilization:
